# Generated by Django 2.1.3 on 2019-08-15 10:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LogInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(blank=True, max_length=32, null=True, verbose_name='服务名称')),
                ('kafka', models.CharField(blank=True, max_length=32, null=True, verbose_name='kafka服务器地址')),
                ('topic', models.CharField(blank=True, max_length=32, null=True, verbose_name='kafka topic')),
                ('log_path', models.CharField(blank=True, max_length=256, null=True, verbose_name='日志路径')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='申请时间')),
            ],
        ),
    ]
