# Generated by Django 2.1.3 on 2019-08-20 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logconsumer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginfo',
            name='task_id',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='task id'),
        ),
    ]
