# Generated by Django 2.1.3 on 2019-08-20 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logconsumer', '0003_auto_20190820_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginfo',
            name='service_name',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True, verbose_name='服务名称'),
        ),
        migrations.AlterField(
            model_name='loginfo',
            name='topic',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True, verbose_name='kafka topic'),
        ),
    ]
