# Generated by Django 2.1.3 on 2019-08-20 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logconsumer', '0005_auto_20190820_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginfo',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'running'), (1, 'stop')], default=0, verbose_name='任务状态'),
        ),
    ]
